import { Inter } from '@next/font/google'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <meta
                    content="width=device-width, initial-scale=1"
                    name="viewport"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main className={styles.main}>
                <div className={styles.title}>
                    <h1 className={inter.className}>Gallery in</h1>
                    <Image
                        alt="next logo"
                        height={100}
                        src="/next.svg"
                        title="Next"
                        width={100}
                    />
                </div>
            </main>
        </>
    )
}
